### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by furqon3009** [AGI-Labs/continual_rl#7]
Hi,

I try to run this command: python main.py --policy ppo --experiment mini_atari_3_tasks_3_cycles
and I got this error:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from torch.utils.tensorboard.writer import SummaryWriter
  File "/home/user/anaconda3/envs/cora2/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/home/user/anaconda3/envs/cora2/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 18, in <module>
    from ._convert_np import make_np
  File "/home/user/anaconda3/envs/cora2/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "/home/user/anaconda3/envs/cora2/lib/python3.7/site-packages/caffe2/python/workspace.py", line 15, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'

Is there anything that I missed? 
Thank you

**Comment by SamNPowers** [comment]
Hey,

Could you try doing "pip install future"? If that works, I might need to add it to our requirements. (See https://stackoverflow.com/questions/57599555/modulenotfounderror-no-module-named-past-when-installing-tensorboard-with-py).

If that doesn't work, could you send the output of pip list?

Please let me know if you encounter other issues with ppo -- it's one of the least well-exercised methods.
